# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  # Azure CLI login
  - task: AzureCLI@2
    displayName: 'Azure CLI Login'
    inputs:
      azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION>'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo 'Logged in to Azure CLI.'

  # Set variables for storage account and static files directory
  - script: |
      echo "##vso[task.setvariable variable=storageAccountName]stcoreprod59o7"
      echo "##vso[task.setvariable variable=staticFilesDir]$(Build.SourcesDirectory)/modules/core/static"
    displayName: 'Set pipeline variables'

  # Upload static website files to $web container
  - task: AzureCLI@2
    displayName: 'Upload static website files to $web container'
    inputs:
      azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION>'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload-batch \
          --account-name $(storageAccountName) \
          --destination '$web' \
          --source $(staticFilesDir) \
          --auth-mode login
